app:
    resource: '@AppBundle/Controller/'
    type: annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

users:
    type: rest
    resource: "@AppBundle/Controller/ApiUserController.php"

pages:
    type: rest
    resource: "@AppBundle/Controller/ApiPageController.php"

revisions:
    type: rest
    parent: pages
    resource: "@AppBundle/Controller/ApiPageController.php"

ratings:
    type: rest
    resource: "@AppBundle/Controller/ApiPageController.php"