# FOSRest Routing
users:
    type: rest
    resource: AppBundle\Controller\ApiUserController

pages:
    type: rest
    resource: AppBundle\Controller\ApiPageController

revisions:
    type: rest
    parent: pages
    resource: AppBundle\Controller\ApiPageRevisionController

ratings:
    type: rest
    resource: AppBundle\Controller\ApiPageController